'use client';

import { motion } from 'framer-motion';
import { useState } from 'react';

interface Response {
  id: string;
  query: string;
  synthesized: string;
  individual: Array<{
    model: string;
    response: string;
    confidence: number;
    time: number;
  }>;
  totalTime: number;
  timestamp: Date;
}

interface ResponseDisplayProps {
  responses: Response[];
}

export default function ResponseDisplay({ responses }: ResponseDisplayProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const latestResponse = responses[responses.length - 1];

  return (
    <motion.div
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 50 }}
      className="fixed inset-x-0 bottom-0 max-h-[60vh] overflow-y-auto bg-slate-900/95 backdrop-blur-xl border-t border-cyan-500/30 p-8"
    >
      {/* Synthesized Response */}
      <div className="max-w-4xl mx-auto">
        <div className="flex items-start justify-between mb-4">
          <h3 className="text-xl font-semibold text-cyan-400">Synthesized Response</h3>
          <div className="flex items-center gap-4 text-sm text-slate-400">
            <span>{latestResponse.individual.length} agents</span>
            <span>{latestResponse.totalTime.toFixed(2)}s</span>
          </div>
        </div>

        <div className="bg-slate-800/50 border border-cyan-500/20 rounded-xl p-6 mb-6">
          <p className="text-white leading-relaxed whitespace-pre-wrap">
            {latestResponse.synthesized}
          </p>
        </div>

        {/* Individual Agent Responses */}
        <button
          onClick={() => setExpandedId(expandedId ? null : latestResponse.id)}
          className="text-sm text-cyan-400 hover:text-cyan-300 mb-4 flex items-center gap-2"
        >
          <span>{expandedId ? 'Hide' : 'Show'} Individual Responses</span>
          <svg
            className={`w-4 h-4 transition-transform ${expandedId ? 'rotate-180' : ''}`}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        {expandedId && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {latestResponse.individual.map((resp, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: idx * 0.1 }}
                className="bg-slate-800/30 border border-slate-700 rounded-lg p-4"
              >
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-medium text-sm text-white">{resp.model}</h4>
                  <div className="flex items-center gap-2">
                    <div className="text-xs text-slate-500">{resp.time.toFixed(2)}s</div>
                    <div className={`text-xs px-2 py-0.5 rounded-full ${
                      resp.confidence > 0.8
                        ? 'bg-green-500/20 text-green-400'
                        : resp.confidence > 0.5
                        ? 'bg-yellow-500/20 text-yellow-400'
                        : 'bg-red-500/20 text-red-400'
                    }`}>
                      {(resp.confidence * 100).toFixed(0)}%
                    </div>
                  </div>
                </div>
                <p className="text-sm text-slate-300 line-clamp-4">{resp.response}</p>
              </motion.div>
            ))}
          </div>
        )}

        {/* Export Options */}
        <div className="mt-6 pt-6 border-t border-slate-700 flex gap-3">
          <button
            onClick={() => {
              navigator.clipboard.writeText(latestResponse.synthesized);
            }}
            className="px-4 py-2 bg-cyan-500/20 border border-cyan-500/50 rounded-lg hover:bg-cyan-500/30 transition-colors text-sm"
          >
            Copy Response
          </button>

          <button
            onClick={() => {
              const markdown = `# Query\n${latestResponse.query}\n\n# Response\n${latestResponse.synthesized}\n\n---\n**Generated by ${latestResponse.individual.length} AI agents in ${latestResponse.totalTime.toFixed(2)}s**`;
              const blob = new Blob([markdown], { type: 'text/markdown' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = `0rb-response-${Date.now()}.md`;
              a.click();
            }}
            className="px-4 py-2 bg-blue-500/20 border border-blue-500/50 rounded-lg hover:bg-blue-500/30 transition-colors text-sm"
          >
            Export Markdown
          </button>

          <button
            onClick={() => {
              const json = JSON.stringify(latestResponse, null, 2);
              const blob = new Blob([json], { type: 'application/json' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = `0rb-response-${Date.now()}.json`;
              a.click();
            }}
            className="px-4 py-2 bg-purple-500/20 border border-purple-500/50 rounded-lg hover:bg-purple-500/30 transition-colors text-sm"
          >
            Export JSON
          </button>
        </div>
      </div>
    </motion.div>
  );
}
