#!/usr/bin/env python3
"""
GENERATOR AGENT
Creates code from natural language specifications.

The first step in the Builder Swarm pipeline.
"""
import os
import sys
import asyncio
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional, List
from dataclasses import dataclass

sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from ai_connectors import AIOrchestrator
    AI_AVAILABLE = True
except ImportError:
    AI_AVAILABLE = False


@dataclass
class GenerationRequest:
    """Request to generate code"""
    description: str
    target_path: str
    language: str = "python"
    framework: Optional[str] = None
    context: Dict[str, Any] = None
    examples: List[str] = None


@dataclass
class GenerationResult:
    """Result of code generation"""
    success: bool
    code: str
    target_path: str
    tokens_used: int = 0
    cost: float = 0.0
    errors: List[str] = None


class CodeGenerator:
    """
    Generates code from natural language descriptions.

    Supports:
    - Python modules and scripts
    - Test files
    - Configuration files
    - Documentation
    """

    TEMPLATES = {
        "python_module": '''#!/usr/bin/env python3
"""
{docstring}

Generated by Builder Swarm - {timestamp}
"""
{imports}

{code}

if __name__ == "__main__":
    main()
''',
        "python_class": '''class {name}:
    """
    {docstring}
    """

    def __init__(self{params}):
        {init_body}

{methods}
''',
        "python_function": '''def {name}({params}) -> {return_type}:
    """
    {docstring}

    Args:
        {args_doc}

    Returns:
        {returns_doc}
    """
    {body}
''',
    }

    def __init__(self):
        self.ai = AIOrchestrator() if AI_AVAILABLE else None
        self.generations = 0
        self.total_tokens = 0
        self.total_cost = 0.0

    async def generate(self, request: GenerationRequest) -> GenerationResult:
        """Generate code from request"""
        self.generations += 1

        prompt = self._build_prompt(request)

        if not self.ai:
            # Fallback: generate stub
            code = self._generate_stub(request)
            return GenerationResult(
                success=True,
                code=code,
                target_path=request.target_path,
                errors=["AI unavailable - generated stub"]
            )

        try:
            result = await self.ai.generate(prompt, task_type="code", complexity=0.8)

            if result.get("success"):
                code = result.get("content", "")
                tokens = result.get("tokens_used", 0)
                cost = result.get("cost", 0.0)

                self.total_tokens += tokens
                self.total_cost += cost

                # Post-process code
                code = self._post_process(code, request)

                # Write to file
                self._write_file(request.target_path, code)

                return GenerationResult(
                    success=True,
                    code=code,
                    target_path=request.target_path,
                    tokens_used=tokens,
                    cost=cost,
                )
            else:
                return GenerationResult(
                    success=False,
                    code="",
                    target_path=request.target_path,
                    errors=[result.get("error", "Unknown error")]
                )

        except Exception as e:
            return GenerationResult(
                success=False,
                code="",
                target_path=request.target_path,
                errors=[str(e)]
            )

    def _build_prompt(self, request: GenerationRequest) -> str:
        """Build the generation prompt"""
        prompt = f"""Generate {request.language} code for the following:

DESCRIPTION:
{request.description}

TARGET FILE: {request.target_path}
"""

        if request.framework:
            prompt += f"\nFRAMEWORK: {request.framework}"

        if request.context:
            prompt += f"\nCONTEXT: {request.context}"

        if request.examples:
            prompt += "\nEXAMPLES:\n" + "\n".join(request.examples)

        prompt += """

REQUIREMENTS:
1. Complete, runnable code
2. Proper error handling
3. Type hints where appropriate
4. Clear docstrings
5. Follow best practices

Return ONLY the code, no explanations or markdown."""

        return prompt

    def _post_process(self, code: str, request: GenerationRequest) -> str:
        """Post-process generated code"""
        # Remove markdown code blocks if present
        if code.startswith("```"):
            lines = code.split("\n")
            lines = [l for l in lines if not l.startswith("```")]
            code = "\n".join(lines)

        # Ensure shebang for Python
        if request.language == "python" and not code.startswith("#!"):
            code = "#!/usr/bin/env python3\n" + code

        # Add generation timestamp
        timestamp = datetime.now().isoformat()
        if '"""' in code[:100]:
            # Add to existing docstring
            code = code.replace('"""', f'"""\nGenerated: {timestamp}\n', 1)

        return code.strip() + "\n"

    def _generate_stub(self, request: GenerationRequest) -> str:
        """Generate a stub when AI unavailable"""
        return f'''#!/usr/bin/env python3
"""
{request.description}

Generated: {datetime.now().isoformat()}
Status: STUB - AI unavailable, implement manually
"""

def main():
    """Main entry point - implement based on description above"""
    raise NotImplementedError("{request.description}")


if __name__ == "__main__":
    main()
'''

    def _write_file(self, path: str, content: str):
        """Write content to file"""
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)

    async def generate_module(
        self,
        name: str,
        description: str,
        functions: List[Dict[str, str]] = None,
        output_dir: str = "./generated"
    ) -> GenerationResult:
        """Generate a complete Python module"""
        func_specs = ""
        if functions:
            func_specs = "\n\nFunctions to include:\n"
            for f in functions:
                func_specs += f"- {f['name']}: {f['description']}\n"

        request = GenerationRequest(
            description=f"Python module: {description}{func_specs}",
            target_path=f"{output_dir}/{name}.py",
            language="python"
        )

        return await self.generate(request)

    async def generate_class(
        self,
        name: str,
        description: str,
        methods: List[Dict[str, str]] = None,
        output_dir: str = "./generated"
    ) -> GenerationResult:
        """Generate a Python class"""
        method_specs = ""
        if methods:
            method_specs = "\n\nMethods to include:\n"
            for m in methods:
                method_specs += f"- {m['name']}: {m['description']}\n"

        request = GenerationRequest(
            description=f"Python class '{name}': {description}{method_specs}",
            target_path=f"{output_dir}/{name.lower()}.py",
            language="python"
        )

        return await self.generate(request)

    def get_stats(self) -> Dict[str, Any]:
        """Get generator statistics"""
        return {
            "generations": self.generations,
            "total_tokens": self.total_tokens,
            "total_cost": self.total_cost,
            "ai_available": self.ai is not None,
        }


# CLI
async def main():
    """CLI for code generation"""
    import argparse

    parser = argparse.ArgumentParser(description="Generate code with AI")
    parser.add_argument("description", help="What to generate")
    parser.add_argument("-o", "--output", default="./generated/output.py", help="Output path")
    parser.add_argument("-l", "--language", default="python", help="Programming language")

    args = parser.parse_args()

    generator = CodeGenerator()
    request = GenerationRequest(
        description=args.description,
        target_path=args.output,
        language=args.language
    )

    print(f"Generating: {args.description}")
    result = await generator.generate(request)

    if result.success:
        print(f"Generated: {result.target_path}")
        print(f"Tokens: {result.tokens_used}, Cost: ${result.cost:.6f}")
    else:
        print(f"Failed: {result.errors}")


if __name__ == "__main__":
    asyncio.run(main())
